# Travis CI (http://travis-ci.org) control file

sudo: required
dist: trusty

language: c

before_install: ci-tools/travis.sh before_install
install:        ci-tools/travis.sh install
script:         ci-tools/travis.sh script
after_success:  ci-tools/travis.sh after_success
